In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [42]:
#chargement des données d'entrainement
pd.read_csv("abalone.csv", sep=";", names=["Longueur", "Diamètre", "Hauteur", "Poids total", "Poids de la chair", "Poids des organes", "Poids de la coquille","Age"])

,Longueur,Diamètre,Hauteur,Poids total,Poids de la chair,Poids des organes,Poids de la coquille,Age
0,Length,Diameter,Height,Whole_weight,Shucked_weight,Viscera_weight,Shell_weight,Label
1,0.455,0.365,0.095,0.514,0.2245,0.101,0.15,15
2,0.35,0.265,0.09,0.2255,0.0995,0.0485,0.07,7
3,0.53,0.42,0.135,0.677,0.2565,0.1415,0.21,9
4,0.44,0.365,0.125,0.516,0.2155,0.114,0.155,10
...,...,...,...,...,...,...,...,...
4173,0.565,0.45,0.165,0.887,0.37,0.239,0.249,11
4174,0.59,0.44,0.135,0.966,0.439,0.2145,0.2605,10
4175,0.6,0.475,0.205,1.176,0.5255,0.2875,0.308,9
4176,0.625,0.485,0.15,1.0945,0.531,0.261,0.296,10
4177,0.71,0.555,0.195,1.9485,0.9455,0.3765,0.495,12

In [16]:
df

,Longueur,Diamètre,Hauteur,Poids total,Poids de la chair,Poids des organes,Poids de la coquille,Age
0,Length,Diameter,Height,Whole_weight,Shucked_weight,Viscera_weight,Shell_weight,Label
1,0.455,0.365,0.095,0.514,0.2245,0.101,0.15,15
2,0.35,0.265,0.09,0.2255,0.0995,0.0485,0.07,7
3,0.53,0.42,0.135,0.677,0.2565,0.1415,0.21,9
4,0.44,0.365,0.125,0.516,0.2155,0.114,0.155,10
...,...,...,...,...,...,...,...,...
4173,0.565,0.45,0.165,0.887,0.37,0.239,0.249,11
4174,0.59,0.44,0.135,0.966,0.439,0.2145,0.2605,10
4175,0.6,0.475,0.205,1.176,0.5255,0.2875,0.308,9
4176,0.625,0.485,0.15,1.0945,0.531,0.261,0.296,10
4177,0.71,0.555,0.195,1.9485,0.9455,0.3765,0.495,12

In [40]:
#
#df.index
df.drop(df.loc[:0] == 0.index, inplace=True)

SyntaxError: invalid syntax (<ipython-input-40-7f87564762f9>, line 3)

In [14]:
df

,Longueur,Diamètre,Hauteur,Poids total,Poids de la chair,Poids des organes,Poids de la coquille
Age,,,,,,,
15,0.455,0.365,0.095,0.514,0.2245,0.101,0.15
7,0.35,0.265,0.09,0.2255,0.0995,0.0485,0.07
9,0.53,0.42,0.135,0.677,0.2565,0.1415,0.21
10,0.44,0.365,0.125,0.516,0.2155,0.114,0.155
7,0.33,0.255,0.08,0.205,0.0895,0.0395,0.055
...,...,...,...,...,...,...,...
11,0.565,0.45,0.165,0.887,0.37,0.239,0.249
10,0.59,0.44,0.135,0.966,0.439,0.2145,0.2605
9,0.6,0.475,0.205,1.176,0.5255,0.2875,0.308
10,0.625,0.485,0.15,1.0945,0.531,0.261,0.296
12,0.71,0.555,0.195,1.9485,0.9455,0.3765,0.495